### ISSUE TITLE
Failure the find correct interval (for `:CICO_ONE_PASS`, `:LIN_EXTRAPOL` suceeds)

### ISSUE THREAD

**Issue by TorkelE** [insysbio/LikelihoodProfiler.jl#11]
I have a case where I wish to compute the likelihood profile interval. In this case I have done it manually (by brute forcing) just for comparison. Here is the full profile, and the threshold value plotted out:
![image](https://github.com/insysbio/LikelihoodProfiler.jl/assets/18099310/1f48743f-c113-40d5-80fe-050fb875c390)
(the full range is like `(1e-3,1e8)`)

Here, I should get an interval from somewhere around `1e4` to `1e8` (where we hit the boundary).

I first try using the `:CICO_ONE_PASS` method, but it seems to fail:
```
conf_int_1 = get_interval(start_p, p_idx, f, :CICO_ONE_PASS; loss_crit, theta_bounds, scan_bounds)
```
gives:
![image](https://github.com/insysbio/LikelihoodProfiler.jl/assets/18099310/89cc9952-a0e3-47aa-bb13-8850ab1f1fb4)
![image](https://github.com/insysbio/LikelihoodProfiler.jl/assets/18099310/f9f524ea-db18-43c4-85a2-1ec3f1c7df2c)
Here, it claims to have found the left boundary, but it clearly did not. Also, it gives a `ParamIntervl` of `[8.0, >8,0]`, which I do not know how to interpret.

Using `:LIN_EXTRAPOL` it works fine:
```
conf_int_2 = get_interval(start_p, p_idx, f, :LIN_EXTRAPOL; loss_crit, theta_bounds, scan_bounds)
```
![image](https://github.com/insysbio/LikelihoodProfiler.jl/assets/18099310/5523904e-29df-46ca-99af-9b2c5490d1f2)
![image](https://github.com/insysbio/LikelihoodProfiler.jl/assets/18099310/31c67fc6-2042-4328-a652-b3f9f3128eca)

Why did the first one fail? Is there a good way to reliably solve this, or at least figure out that it failed? I am scanning a large number of intervals for a model, and want to compute how the size of the interval depends on the data's quality. This means while for a singular case I can look at the plot and see what is going on, for my application I cannot. I would need to figure out how to automate this. I have OK amount of compute, so I could try and compute the itnerval using all methods, but am unsure how to figure out that one method failed.

I could try to provide more detail on the cost function (but it will mean lots of code, I create the cost function using PEtab, and several files with data)

**Comment by ivborissov** [comment]
It seems the initial point didn't change , so the optimizer actually failed to find the lower bound, but didn't report it correctly. It's hard to diagnose the issue without the model/cost func. Is it sharable, e.g. in `PEtab` format? 
In general it is possible to change tolerance setup `scan_tol` or use a different algorithm `local_alg` from `NLopt` package (e.g. `LN_SBPLX`), but `NLopt` is the main limitation now. The way Augemnted Lagrangian is implemented there it is not possible to directly control the cost func closenes to the threashold (only indirectly through `scan_tol`). Reimpementing it julia is what we plan to do to get more control on termination, convergence and potential failures.

**Comment by TorkelE** [comment]
I tried increasing `scan_tol` for its default (`1e-3`) to `1e-6`. I still get the same failure, however, the run time increases from 2 seconds to 100.

I could try to give you an example, but unfortunately it is not trivial, everything is generated by a code base over several files. If you'd like to have a look, I am happy to send you it.

In the meantime, would there be a simple way to detect that something like this has happened (so that I could e.g. throw a warning)?

**Comment by ivborissov** [comment]
Sure, if you can share the files (slack or iv.borissov at gmail.com) that will be very helpful !
Not sure about a quick fix... as it is only a guess, that the solver didn't move from the initial point and the termination criteria was reported wrong.

**Comment by TorkelE** [comment]
I am preparing examples for you to look at. Can I send you them over Slack?

**Comment by ivborissov** [comment]
@TorkelE Yes, sure

**Comment by TorkelE** [comment]
Seems to work, I think I misinterpreted the plots.
