### ISSUE TITLE
Liklihood profile does not computed all the way to identifiability level.

### ISSUE THREAD

**Issue by TorkelE** [insysbio/LikelihoodProfiler.jl#9]
I am fitting a set of ODEs to data, minimizing a cost function to do so. After I have  found a parameter set I want to use profile likelihood analysis to evaluate practical identifiability. However, I do not seem to get the complete evaluation?
```julia
# Getting these functions is quite convoluted, but in principle it is just the fitting of and ODE to data using l2 distance.
cost_func(p) # My cost function.
opt_parameterset The parameter set that minimises the cost function.
opt_val # The minimal value of the cost function

using LikelihoodProfiler

@time liklihood_profile = get_interval(
    opt_parameterset,                 # starting point
    1,                                                      # parameter component to analyze
    cost_func,                                              # profile function
    :LIN_EXTRAPOL;                                          # method
    loss_crit = 10*opt_val                     # critical level of loss function
)
plot(liklihood_profile)
```
![image](https://github.com/insysbio/LikelihoodProfiler.jl/assets/18099310/9dc80531-c178-441c-9010-9779f724cfb4)

The evaluation of the likelihood profile only takes like 20 second as well, so it feel it could have evaluate more of it?

Is there a way to extend the evaluation?

**Comment by ivborissov** [comment]
Apologies for getting back to you so late. In general `LIN_EXTRAPOL` is an experimental method tested on rather simple use-cases. It is recommended to use `:CICO_ONE_PASS`. If you can share the problem or a MWE we can work it out together.

**Comment by TorkelE** [comment]
Thank you, I will try `:CICO_ONE_PASS` once I have trouble. I restarted everything this week, and got it working now.
